# 将pynput的key转换为pyautogui的key
from typing import Union, List

from pynput import keyboard

_KEY_TABLE = {keyboard.Key.alt: 'alt', keyboard.Key.alt_l: 'altleft', keyboard.Key.alt_r: 'altright',
              keyboard.Key.alt_gr: None, keyboard.Key.backspace: 'backspace',
              keyboard.Key.caps_lock: 'capslock',
              keyboard.Key.cmd: 'win', keyboard.Key.cmd_l: 'winleft', keyboard.Key.cmd_r: 'winright',
              keyboard.Key.ctrl: 'ctrl',
              keyboard.Key.ctrl_l: 'ctrlleft', keyboard.Key.ctrl_r: 'ctrlright', keyboard.Key.delete: 'delete',
              keyboard.Key.down: 'down', keyboard.Key.end: 'end', keyboard.Key.enter: 'enter',
              keyboard.Key.esc: 'esc', keyboard.Key.f1: 'f1', keyboard.Key.f2: 'f2', keyboard.Key.f3: 'f3',
              keyboard.Key.f4: 'f4', keyboard.Key.f5: 'f5', keyboard.Key.f6: 'f6', keyboard.Key.f7: 'f7',
              keyboard.Key.f8: 'f8', keyboard.Key.f9: 'f9', keyboard.Key.f10: 'f10',
              keyboard.Key.f11: 'f11', keyboard.Key.f12: 'f12', keyboard.Key.f13: 'f13',
              keyboard.Key.f14: 'f14',
              keyboard.Key.f15: 'f15', keyboard.Key.f16: 'f16', keyboard.Key.f17: 'f17',
              keyboard.Key.f18: 'f18',
              keyboard.Key.f19: 'f19', keyboard.Key.f20: 'f20', keyboard.Key.home: 'home',
              keyboard.Key.left: 'left',
              keyboard.Key.page_down: 'pagedown', keyboard.Key.page_up: 'pageup', keyboard.Key.right: 'right',
              keyboard.Key.shift: 'shift', keyboard.Key.shift_l: 'shiftleft',
              keyboard.Key.shift_r: 'shiftright',
              keyboard.Key.space: 'space', keyboard.Key.tab: 'tab', keyboard.Key.up: 'up',
              keyboard.Key.media_play_pause: 'playpause', keyboard.Key.media_volume_mute: 'volumemute',
              keyboard.Key.media_volume_down: 'volumedown', keyboard.Key.media_volume_up: 'volumeup',
              keyboard.Key.insert: 'insert', keyboard.Key.menu: None,
              keyboard.Key.num_lock: 'numlock', keyboard.Key.pause: 'pause',
              keyboard.Key.print_screen: 'printscreen', keyboard.Key.scroll_lock: 'scrolllock',
              '96': '0', '97': '1', '98': '2', '99': '3', '100': '4', '101': '5', '102': '6', '103': '7',
              '104': '8', '105': '9',
              }

_KEYCODE_TABLE = {r"'\x01'": ['ctrl', 'a'],
                  r"'\x02'": ['ctrl', 'b'],
                  r"'\x03'": ['ctrl', 'c'],
                  r"'\x04'": ['ctrl', 'd'],
                  r"'\x05'": ['ctrl', 'e'],
                  r"'\x06'": ['ctrl', 'f'],
                  r"'\x07'": ['ctrl', 'g'],
                  r"'\x08'": ['ctrl', 'h'],
                  r"'\t'": ['ctrl', 'i'],
                  r"'\n'": ['ctrl', 'j'],
                  r"'\x0b'": ['ctrl', 'k'],
                  r"'\x0c'": ['ctrl', 'l'],
                  r"'\r'": ['ctrl', 'm'],
                  r"'\x0e'": ['ctrl', 'n'],
                  r"'\x0f'": ['ctrl', 'o'],
                  r"'\x10'": ['ctrl', 'p'],
                  r"'\x11'": ['ctrl', 'q'],
                  r"'\x12'": ['ctrl', 'r'],
                  r"'\x13'": ['ctrl', 's'],
                  r"'\x14'": ['ctrl', 't'],
                  r"'\x15'": ['ctrl', 'u'],
                  r"'\x16'": ['ctrl', 'v'],
                  r"'\x17'": ['ctrl', 'w'],
                  r"'\x18'": ['ctrl', 'x'],
                  r"'\x19'": ['ctrl', 'y'],
                  r"'\x1a'": ['ctrl', 'z'],
                  r"'\x1f'": ['ctrl', 'shift', '-'],
                  r"<186>": ['ctrl', ';'],
                  r"<187>": ['ctrl', '='],
                  r"<189>": ['ctrl', '-'],
                  r"<192>": ['ctrl', '`'],
                  r"<222>": ['ctrl', r"'"],
                  r"<48>": ['ctrl', '0'],
                  r"<49>": ['ctrl', '1'],
                  r"<50>": ['ctrl', '2'],
                  r"<51>": ['ctrl', '3'],
                  r"<52>": ['ctrl', '4'],
                  r"<53>": ['ctrl', '5'],
                  r"<54>": ['ctrl', '6'],
                  r"<55>": ['ctrl', '7'],
                  r"<56>": ['ctrl', '8'],
                  r"<57>": ['ctrl', '9'],
                  r"'~'": ['shift', '`'],
                  r"'!'": ['shift', '1'],
                  r"'@'": ['shift', '2'],
                  r"'#'": ['shift', '3'],
                  r"'$'": ['shift', '4'],
                  r"'%'": ['shift', '5'],
                  r"'^'": ['shift', '6'],
                  r"'*'": ['shift', '7'],
                  r"'('": ['shift', '8'],
                  r"')'": ['shift', '9'],
                  r"'_'": ['shift', '-'],
                  r"'+'": ['shift', '='],
                  r"':'": ['shift', ';'],
                  r"'\"'": ['shift', "'"],
                  r"'<'": ['shift', ","],
                  r"'{'": ['shift', "["],
                  r"'}'": ['shift', "]"],
                  r"'|'": ['shift', "\\"],
                  r"'?'": ['shift', "/"],
                  }


def convert_key(key_pynput) -> Union[str, List[str], None]:
    """将pynput的key转换为pyautogui的key"""
    if key_pynput in _KEY_TABLE:
        return _KEY_TABLE[key_pynput]
    elif key_pynput in _KEYCODE_TABLE:
        return _KEYCODE_TABLE[key_pynput]
    else:
        return None
